# Generated by Django 4.2.7 on 2025-11-17 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='要转换的英文文本', verbose_name='文本内容')),
                ('tts_type', models.CharField(choices=[('local', '本地生成'), ('cloud', '云服务生成')], default='local', max_length=10, verbose_name='生成方式')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('preurl', models.URLField(blank=True, max_length=500, null=True, verbose_name='预签名URL')),
                ('path', models.CharField(blank=True, max_length=300, null=True, verbose_name='文件路径')),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '音频记录',
                'verbose_name_plural': '音频记录',
                'db_table': 'audio_records',
                'ordering': ['-uptime'],
            },
        ),
    ]
