# Generated by Django 4.2.7 on 2025-12-04 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='视频标题或描述', max_length=200, verbose_name='视频标题')),
                ('preurl', models.URLField(blank=True, max_length=500, null=True, verbose_name='预签名URL')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='本地文件路径')),
                ('object_key', models.CharField(blank=True, max_length=300, null=True, verbose_name='对象存储Key')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '视频记录',
                'verbose_name_plural': '视频记录',
                'db_table': 'video_records',
                'ordering': ['-uptime'],
            },
        ),
    ]
