# Generated by Django 4.2.7 on 2025-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0002_videorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='缩略图存储Key'),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='缩略图URL'),
        ),
    ]
