# Generated by Django 4.2.7 on 2025-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0003_add_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='subtitle_key',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='字幕存储Key'),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='subtitle_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='字幕文件名'),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='subtitle_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='字幕URL'),
        ),
    ]
