# Generated by Django 4.2.7 on 2025-12-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0004_add_video_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='category',
            field=models.CharField(choices=[('default', '默认'), ('education', '教育'), ('entertainment', '娱乐'), ('technology', '科技'), ('life', '生活'), ('music', '音乐'), ('movie', '电影'), ('game', '游戏'), ('news', '新闻'), ('sports', '体育'), ('other', '其他')], default='default', max_length=20, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='tags',
            field=models.CharField(blank=True, help_text='多个标签用逗号分隔', max_length=500, null=True, verbose_name='标签'),
        ),
    ]
